export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  resetSuccess: '/reset-success',
  verifyEmail: '/verify-email',
  dashboard: '/dashboard',
  jobs: {
    jobMatch: '/jobs/job-match',
    jobDetail: '/jobs/:id',
    customCv: '/jobs/custom-cv',
    cvEdit: '/jobs/cv/:id/edit',
    cvAiEdit: '/jobs/cv/:id/ai-edit',
  },
  freelance: {
    projectMatch: '/freelance/project-match',
    projectDetail: '/freelance/projects/:id',
    createProposal: '/freelance/create-proposal',
    proposal: '/freelance/proposal',
  },
  cvBuilder: '/cv-builder',
  notifications: '/notifications',
  settings: {
    profile: '/settings/profile',
    preferences: '/settings/preferences',
    security: '/settings/security',
  },
} as const
